# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "967b40b67457789fe725d9005bd03c20"
name = "CRUD-app"
handle = "crud-app-7"
application_url = "https://heavily-evaluation-victory-site.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_locations, write_inventory"

[auth]
redirect_urls = [
  "https://heavily-evaluation-victory-site.trycloudflare.com/auth/callback",
  "https://heavily-evaluation-victory-site.trycloudflare.com/auth/shopify/callback",
  "https://heavily-evaluation-victory-site.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
